Fix missing semi-colon in leapsecond test code
Error message was:
../../tests/ntpd/leapsec.c:771:22: error: expected ';' after do/while statement
        TEST_ASSERT_TRUE(rc)
                            ^
                            ;
1 error generated.