Fix warnings on Solaris about clock_settime() being implicitly defined
../../libntp/clockwork.c:83:2: warning: implicit declaration of function 'clock_settime' [-Wimplicit-function-declaration]
../../ntpfrob/bumpclock.c:26:5: warning: implicit declaration of function 'clock_settime' [-Wimplicit-function-declaration]
../../ntpfrob/bumpclock.c:41:5: warning: implicit declaration of function 'clock_settime' [-Wimplicit-function-declaration]

Commit "Reduce clutter from ./waf -v" caused definitions like __EXTENSIONS__
and _POSIX_C_SOURCE to now only be defined in config.h, instead of being in the
command line passed to the compiler.

Therefore we must include config.h before including system headers to get the
correct feature macros to be set so that we get POSIX versions of functions and
symbols.

Fixes Gitlab issue #422