Fix warning about implicit definition of clock_gettime on Solaris
../../ntpfrob/precision.c: In function 'default_get_resolution':
../../ntpfrob/precision.c:78:2: warning: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
  clock_gettime(CLOCK_REALTIME, &tp);
  ^

Include config.h before system headers so that "standards" macros get defined
early enough