ntpviz: Fix temp file binary vs. text
This fixes the following error from os.write() on Python 3:
TypeError: a bytes-like object is required, not 'str'