Readline on LEDE requires the ncurses library
[184/185] Linking build/main/ntpq/ntpq
libntp/libntp.a(ntp_lineedit.c.1.o): In function `ntp_readline':
ntp_lineedit.c:(.text+0xf0): undefined reference to `readline'
ntp_lineedit.c:(.text+0x10c): undefined reference to `add_history'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/sdwalker/lede/build_dir/target-mips_34kc_musl-1.1.15/NTPsec-0.9.5-20160819/build/main'
Build failed
 -> task in 'ntpq' failed (exit status 1):
        {task 36811360: cprogram ntpq.c.2.o,ntpq-subs.c.2.o,version.c.2.o -> ntpq}
['ccache_cc', 'ntpq/ntpq.c.2.o', 'ntpq/ntpq-subs.c.2.o', 'ntpq/version.c.2.o', '-o', '/home/sdwalker/lede/build_dir/target-mips_34kc_musl-1.1.15/NTPsec-0.9.5-20160819/build/main/ntpq/ntpq', '-Wl,-Bstatic', '-Llibntp', '-Llibsodium', '-Llibisc', '-lntp', '-lsodium', '-lisc', '-Wl,-Bdynamic', '-lm', '-lrt', '-lpthread', '-lcrypto', '-L/home/sdwalker/lede/stag$
Makefile:219: recipe for target '/home/sdwalker/lede/build_dir/target-mips_34kc_musl-1.1.15/NTPsec-0.9.5-20160819/.built' failed
make[2]: *** [/home/sdwalker/lede/build_dir/target-mips_34kc_musl-1.1.15/NTPsec-0.9.5-20160819/.built] Error 1

Signed-off-by: Stephen Walker <stephendwalker+github@gmail.com>