Fix typos and make sure defaults are set in pyntpq
Errors were:
$ ./ntpq/pyntpq -p
Traceback (most recent call last):
  File "./ntpq/pyntpq", line 668, in <module>
    interpreter.ccmd.append("peers")
AttributeError: ntpq_interpreter instance has no attribute 'ccmd'

$ ./ntpq/pyntpq -d
Traceback (most recent call last):
  File "./ntpq/pyntpq", line 655, in <module>
    interpreter.debug += 1
AttributeError: ntpq_interpreter instance has no attribute 'debug'