Fix build error on Solaris regarding siginfo_t not being defined
'gcc', '-fstack-protector-all', '-Wshadow', '-Wpacked', '-Wcast-qual', '-Wmissing-declarations', '-Wdisabled-optimization', '-Wimplicit-function-declaration', '-Winvalid-pch', '-Wpointer-arith', '-Wwrite-strings', '-Winit-self', '-Wfloat-equal', '-Wformat', '-Wformat-security', '-Wsuggest-attribute=noreturn', '-fPIC', '-O1', '-Wall', '-Wextra', '-Wmissing-prototypes', '-Wstrict-prototypes', '-Wundef', '-Wunused', '-std=c99', '-D_GNU_SOURCE', '-I../host/ntpd', '-I../../ntpd', '-I..', '-I../../include', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '../../ntpd/ntp_sandbox.c', '-c', '-o/home/worker/Buildbot/status/full_Solaris_4.8.2_GCC_4.8.2_refclocks/build/build/main/ntpd/ntp_sandbox.c.18.o']
In file included from ../../ntpd/ntp_sandbox.c:51:0:
../../include/ntp_stdlib.h:128:53: error: unknown type name 'siginfo_t'
 extern void signal_no_reset1(int, void (*func)(int, siginfo_t *, void *));
                                                     ^

Commit "Reduce clutter from ./waf -v" caused definitions like __EXTENSIONS__
and _POSIX_C_SOURCE to now only be defined in config.h, instead of being in the
command line passed to the compiler.

Therefore we must include config.h before including system headers to get the
correct feature macros to be set so that we get POSIX versions of functions and
symbols.