Fix exception handling in ntptrace
Reference CalledProcessError exception correctly. Fixes:
NameError: global name 'CalledProcessError' is not defined

Use python2/python3 compatible format for exceptions.

Force stderr to stdout in subprocess.check_output() so that e.output has data later.